# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

inhibit_all_warnings!

target 'WWDC Family' do

pod 'Fabric'
pod 'Crashlytics'
pod 'FCUtilities', :git => 'https://github.com/marcoarment/FCUtilities.git'
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'INTULocationManager'
pod 'MBProgressHUD', '~> 1.0'
pod 'Texture', :git => 'https://github.com/texturegroup/Texture.git'
pod 'NSDate+TimeAgo'

end
