//
//  DDFUser.h
//  Autogenerated by plank
//
//  DO NOT EDIT - EDITS WILL BE OVERWRITTEN
//  @generated
//

#import <Foundation/Foundation.h>
#import "PlankModelRuntime.h"
@class DDFUserBuilder;

NS_ASSUME_NONNULL_BEGIN

@interface DDFUser : NSObject<NSCopying, NSSecureCoding>
@property (nonatomic, assign, readonly) double latitude;
@property (nullable, nonatomic, copy, readonly) NSString * name;
@property (nullable, nonatomic, copy, readonly) NSString * identifier;
@property (nullable, nonatomic, copy, readonly) NSDate * createdAt;
@property (nullable, nonatomic, copy, readonly) NSURL * avatar;
@property (nullable, nonatomic, copy, readonly) NSString * twitterID;
@property (nullable, nonatomic, copy, readonly) NSDate * updatedAt;
@property (nullable, nonatomic, copy, readonly) NSString * twitterUsername;
@property (nonatomic, assign, readonly) double longitude;
@property (nullable, nonatomic, copy, readonly) NSString * country;
+ (NSString *)className;
+ (NSString *)polymorphicTypeIdentifier;
+ (instancetype)modelObjectWithDictionary:(NSDictionary *)dictionary;
- (instancetype)initWithModelDictionary:(NS_VALID_UNTIL_END_OF_SCOPE NSDictionary *)modelDictionary;
- (instancetype)initWithBuilder:(DDFUserBuilder *)builder;
- (instancetype)initWithBuilder:(DDFUserBuilder *)builder initType:(PlankModelInitType)initType;
- (instancetype)copyWithBlock:(PLANK_NOESCAPE void (^)(DDFUserBuilder *builder))block;
- (BOOL)isEqualToUser:(DDFUser *)anObject;
- (instancetype)mergeWithModel:(DDFUser *)modelObject;
- (instancetype)mergeWithModel:(DDFUser *)modelObject initType:(PlankModelInitType)initType;
- (NSDictionary *)dictionaryObjectRepresentation;
@end

@interface DDFUserBuilder : NSObject
@property (nonatomic, assign, readwrite) double latitude;
@property (nullable, nonatomic, copy, readwrite) NSString * name;
@property (nullable, nonatomic, copy, readwrite) NSString * identifier;
@property (nullable, nonatomic, copy, readwrite) NSDate * createdAt;
@property (nullable, nonatomic, copy, readwrite) NSURL * avatar;
@property (nullable, nonatomic, copy, readwrite) NSString * twitterID;
@property (nullable, nonatomic, copy, readwrite) NSDate * updatedAt;
@property (nullable, nonatomic, copy, readwrite) NSString * twitterUsername;
@property (nonatomic, assign, readwrite) double longitude;
@property (nullable, nonatomic, copy, readwrite) NSString * country;
- (instancetype)initWithModel:(DDFUser *)modelObject;
- (DDFUser *)build;
- (void)mergeWithModel:(DDFUser *)modelObject;
@end

NS_ASSUME_NONNULL_END
